set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]


############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]

##############reset key define##################
set_property PACKAGE_PIN T6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]
####  AN5642 on AX7103 J13
set_property PACKAGE_PIN W16 [get_ports {cmos2_db[9]}]
set_property PACKAGE_PIN W15 [get_ports {cmos2_sda}]
set_property PACKAGE_PIN V17 [get_ports {cmos2_db[6]}]
set_property PACKAGE_PIN W17 [get_ports {cmos2_scl}]
set_property PACKAGE_PIN U15 [get_ports {cmos2_db[7]}]
set_property PACKAGE_PIN V15 [get_ports {cmos2_db[2]}]
set_property PACKAGE_PIN AB21 [get_ports {cmos2_href}]
set_property PACKAGE_PIN AB22 [get_ports {cmos2_db[8]}]
set_property PACKAGE_PIN AA21 [get_ports {cmos2_db[3]}]
set_property PACKAGE_PIN AA20 [get_ports {cmos2_rst_n}]
set_property PACKAGE_PIN AB20 [get_ports {cmos2_db[4]}]
set_property PACKAGE_PIN AA19 [get_ports {cmos2_db[5]}]
set_property PACKAGE_PIN AA18 [get_ports {cmos2_db[1]}]
set_property PACKAGE_PIN AB18 [get_ports {cmos2_db[0]}]
set_property PACKAGE_PIN T20 [get_ports {cmos2_vsync}]
set_property PACKAGE_PIN Y17 [get_ports {cmos2_pclk}]
set_property PACKAGE_PIN W21 [get_ports {cmos1_sda}]
set_property PACKAGE_PIN T21 [get_ports {cmos1_db[9]}]
set_property PACKAGE_PIN U21 [get_ports {cmos1_db[8]}]
set_property PACKAGE_PIN Y21 [get_ports {cmos1_scl}]
set_property PACKAGE_PIN Y22 [get_ports {cmos1_db[5]}]
set_property PACKAGE_PIN W20 [get_ports {cmos1_db[3]}]
set_property PACKAGE_PIN W19 [get_ports {cmos1_db[4]}]
set_property PACKAGE_PIN Y19 [get_ports {cmos1_db[6]}]
set_property PACKAGE_PIN Y18 [get_ports {cmos1_db[0]}]
set_property PACKAGE_PIN V22 [get_ports {cmos1_db[7]}]
set_property PACKAGE_PIN U22 [get_ports {cmos1_db[1]}]
set_property PACKAGE_PIN T18 [get_ports {cmos1_db[2]}]
set_property PACKAGE_PIN R18 [get_ports {cmos1_pclk}]
set_property PACKAGE_PIN R14 [get_ports {cmos1_href}]
set_property PACKAGE_PIN P14 [get_ports {cmos1_vsync}]
set_property PACKAGE_PIN N13 [get_ports {cmos1_rst_n}]



set_property IOSTANDARD LVCMOS33 [get_ports cmos1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_rst_n]

create_clock -period 11.904 [get_ports cmos1_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]
set_input_delay -clock [get_clocks cmos1_pclk]  2.200 [get_ports {cmos1_db[*]}]
set_input_delay -clock [get_clocks cmos1_pclk]  2.200 [get_ports cmos1_href]
set_input_delay -clock [get_clocks cmos1_pclk] -min -add_delay 2.200 [get_ports cmos1_vsync]
set_input_delay -clock [get_clocks cmos1_pclk] -max -add_delay 4.000 [get_ports cmos1_vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_pclk}]

create_clock -period 11.904 [get_ports cmos2_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos2_pclk_IBUF]
set_input_delay -clock [get_clocks cmos2_pclk] -min -add_delay 2.200 [get_ports {cmos2_db[*]}]
set_input_delay -clock [get_clocks cmos2_pclk] -max -add_delay 4.000 [get_ports {cmos2_db[*]}]
set_input_delay -clock [get_clocks cmos2_pclk] -min -add_delay 2.200 [get_ports cmos2_href]
set_input_delay -clock [get_clocks cmos2_pclk] -max -add_delay 4.000 [get_ports cmos2_href]
set_input_delay -clock [get_clocks cmos2_pclk] -min -add_delay 2.200 [get_ports cmos2_vsync]
set_input_delay -clock [get_clocks cmos2_pclk] -max -add_delay 4.000 [get_ports cmos2_vsync]
set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_out1_video_pll]
set_false_path -from [get_clocks clk_out1_video_pll] -to [get_clocks clk_pll_i]

set_property PACKAGE_PIN M13 [get_ports hdmi_out_clk]
set_property PACKAGE_PIN V14 [get_ports {hdmi_out_data[0]}]
set_property PACKAGE_PIN H14 [get_ports {hdmi_out_data[1]}]
set_property PACKAGE_PIN J14 [get_ports {hdmi_out_data[2]}]
set_property PACKAGE_PIN K13 [get_ports {hdmi_out_data[3]}]
set_property PACKAGE_PIN K14 [get_ports {hdmi_out_data[4]}]
set_property PACKAGE_PIN L13 [get_ports {hdmi_out_data[5]}]
set_property PACKAGE_PIN L19 [get_ports {hdmi_out_data[6]}]
set_property PACKAGE_PIN L20 [get_ports {hdmi_out_data[7]}]
set_property PACKAGE_PIN K17 [get_ports {hdmi_out_data[8]}]
set_property PACKAGE_PIN J17 [get_ports {hdmi_out_data[9]}]
set_property PACKAGE_PIN L16 [get_ports {hdmi_out_data[10]}]
set_property PACKAGE_PIN K16 [get_ports {hdmi_out_data[11]}]
set_property PACKAGE_PIN L14 [get_ports {hdmi_out_data[12]}]
set_property PACKAGE_PIN L15 [get_ports {hdmi_out_data[13]}]
set_property PACKAGE_PIN M15 [get_ports {hdmi_out_data[14]}]
set_property PACKAGE_PIN M16 [get_ports {hdmi_out_data[15]}]
set_property PACKAGE_PIN L18 [get_ports {hdmi_out_data[16]}]
set_property PACKAGE_PIN M18 [get_ports {hdmi_out_data[17]}]
set_property PACKAGE_PIN N18 [get_ports {hdmi_out_data[18]}]
set_property PACKAGE_PIN N19 [get_ports {hdmi_out_data[19]}]
set_property PACKAGE_PIN M20 [get_ports {hdmi_out_data[20]}]
set_property PACKAGE_PIN N20 [get_ports {hdmi_out_data[21]}]
set_property PACKAGE_PIN L21 [get_ports {hdmi_out_data[22]}]
set_property PACKAGE_PIN M21 [get_ports {hdmi_out_data[23]}]
set_property PACKAGE_PIN V13 [get_ports hdmi_out_de]
set_property PACKAGE_PIN T15 [get_ports hdmi_out_hs]
set_property PACKAGE_PIN J19 [get_ports hdmi_nreset]
set_property PACKAGE_PIN T14 [get_ports hdmi_out_vs]
set_property PACKAGE_PIN E16 [get_ports hdmi_scl]
set_property PACKAGE_PIN F16 [get_ports hdmi_sda]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_out_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_out_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]
set_property IOB TRUE [get_ports {hdmi_out_data[*]}]
set_property IOB TRUE [get_ports hdmi_out_de]
set_property IOB TRUE [get_ports hdmi_out_hs]
set_property IOB TRUE [get_ports hdmi_out_vs]
set_property SLEW FAST [get_ports {hdmi_out_data[*]}]
set_property SLEW FAST [get_ports hdmi_out_de]
set_property SLEW FAST [get_ports hdmi_out_hs]
set_property SLEW FAST [get_ports hdmi_out_vs]
set_property DRIVE 12 [get_ports {hdmi_out_data[*]}]
set_property DRIVE 16 [get_ports hdmi_out_clk]
set_property DRIVE 12 [get_ports hdmi_out_de]
set_property DRIVE 12 [get_ports hdmi_out_hs]



