# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PCIe.xdc

# Block Designs: bd/PCIe/PCIe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe || ORIG_REF_NAME==PCIe}]

# IP: bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_util_ds_buf_0_0 || ORIG_REF_NAME==PCIe_util_ds_buf_0_0}]

# IP: bd/PCIe/ip/PCIe_xdma_0_1/PCIe_xdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1 || ORIG_REF_NAME==PCIe_xdma_0_1}]

# IP: bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_clk_wiz_0_0 || ORIG_REF_NAME==PCIe_clk_wiz_0_0}]

# IP: bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_mig_7series_0_0 || ORIG_REF_NAME==PCIe_mig_7series_0_0}]

# IP: bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==PCIe_rst_mig_7series_0_100M_0}]

# IP: bd/PCIe/ip/PCIe_axi_interconnect_0_1/PCIe_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_axi_interconnect_0_1 || ORIG_REF_NAME==PCIe_axi_interconnect_0_1}]

# IP: bd/PCIe/ip/PCIe_auto_us_0/PCIe_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_auto_us_0 || ORIG_REF_NAME==PCIe_auto_us_0}]

# IP: bd/PCIe/ip/PCIe_auto_cc_0/PCIe_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_auto_cc_0 || ORIG_REF_NAME==PCIe_auto_cc_0}]

# XDC: bd/PCIe/PCIe_ooc.xdc
