# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/exam_ise/pcieddr3/PCIe.cache/wt [current_project]
set_property parent.project_path D:/exam_ise/pcieddr3/PCIe.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/exam_ise/pcieddr3/PCIe.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/hdl/PCIe_wrapper.v
add_files D:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/PCIe.bd
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_0/synth/PCIe_xdma_0_1_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_1/xdma_v3_1_1_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_2/xdma_v3_1_1_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/PCIe_xdma_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/source/PCIe_xdma_0_1_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_xdma_0_1/synth/PCIe_xdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/constraints/PCIe_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/constraints/PCIe_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/PCIe_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_auto_us_0/PCIe_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_auto_us_0/PCIe_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_auto_us_0/PCIe_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_auto_cc_0/PCIe_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_auto_cc_0/PCIe_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/ip/PCIe_auto_cc_0/PCIe_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/PCIe_ooc.xdc]
set_property is_locked true [get_files D:/exam_ise/pcieddr3/PCIe.srcs/sources_1/bd/PCIe/PCIe.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/exam_ise/pcieddr3/PCIe.srcs/constrs_1/new/PCIe.xdc
set_property used_in_implementation false [get_files D:/exam_ise/pcieddr3/PCIe.srcs/constrs_1/new/PCIe.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top PCIe_wrapper -part xc7a100tfgg484-2


write_checkpoint -force -noxdef PCIe_wrapper.dcp

catch { report_utilization -file PCIe_wrapper_utilization_synth.rpt -pb PCIe_wrapper_utilization_synth.pb }
