set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
############## clock define##################
create_clock -period 5 [get_ports sys_clk_p]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]

##############reset key define##################
set_property PACKAGE_PIN T6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS15 [get_ports rst_n]

##############KEY1 define##################
set_property PACKAGE_PIN J21 [get_ports key1]
set_property IOSTANDARD LVCMOS33 [get_ports key1]

############## LCD define##################
set_property PACKAGE_PIN P16 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN R17 [get_ports {lcd_r[1]}]
set_property PACKAGE_PIN R16 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN P15 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN N17 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN P17 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN U16 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN T16 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN U17 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN U18 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN P19 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN R19 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN V18 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN V19 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN U20 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN V20 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN AA9 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN AB10 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN AA10 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN AA11 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN W10 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN V10 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN Y12 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN Y11 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN W12 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN W11 [get_ports {lcd_hsync}]
set_property PACKAGE_PIN AA15 [get_ports {lcd_vsync}]
set_property PACKAGE_PIN AB15 [get_ports {lcd_de}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]




