#!/bin/bash -f
# Vivado (TM) v2017.2 (64-bit)
#
# Filename    : PCIe.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Nov 10 13:29:10 +0800 2017
# IP Build 1909766 on Thu Jun 15 19:58:00 MDT 2017 
#
# usage: PCIe.sh [-help]
# usage: PCIe.sh [-lib_map_path]
# usage: PCIe.sh [-noclean_files]
# usage: PCIe.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'PCIe.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm util_ds_buf_v2_01_a blk_mem_gen_v8_3_6 fifo_generator_v13_1_4 xdma_v3_1_1 lib_cdc_v1_0_2 proc_sys_reset_v5_0_11 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_13 axi_data_fifo_v2_1_12 axi_crossbar_v2_1_14 axi_clock_converter_v2_1_12 axi_protocol_converter_v2_1_13 axi_dwidth_converter_v2_1_13)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "PCIe.sh - Script generated by export_simulation (Vivado v2017.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2017.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work util_ds_buf_v2_01_a $vhdlan_opts \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/1e84/hdl/vhdl/util_ds_buf.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_util_ds_buf_0_0/sim/PCIe_util_ds_buf_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_clock.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_eq.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_drp.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_rate.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_reset.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_sync.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gtp_pipe_rate.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gtp_pipe_drp.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gtp_pipe_reset.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_user.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pipe_wrapper.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_qpll_drp.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_qpll_reset.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_qpll_wrapper.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_rxeq_scan.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_core_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_rx_null_gen.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_rx_pipeline.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_rx.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_tx_pipeline.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_tx_thrtl_ctl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_axi_basic_tx.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_7x.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_bram_7x.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_bram_top_7x.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_brams_7x.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_pipe_lane.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_pipe_misc.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie_pipe_pipeline.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gt_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gt_common.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gtp_cpllpd_ovrd.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gtx_cpllpd_ovrd.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gt_rx_valid_filter_7x.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_gt_wrapper.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/source/PCIe_xdma_0_1_pcie2_ip_pcie2_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_0/sim/PCIe_xdma_0_1_pcie2_ip.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/4158/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_1/sim/xdma_v3_1_1_blk_mem_64_reg_be.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_2/sim/xdma_v3_1_1_blk_mem_64_noreg_be.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/ebc2/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_4 $vhdlan_opts \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/ebc2/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_3/sim/pcie2_fifo_generator_dma_cpl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/ip_4/sim/pcie2_fifo_generator_tgt_brdg.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xdma_v3_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/xdma_v3_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_dma_cpl.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_dma_req.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v2_0/hdl/verilog/PCIe_xdma_0_1_rx_destraddler.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_rx_demux.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_tgt_cpl.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_tgt_req.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_tx_mux.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_axi_stream_intf.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_cfg_sideband.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_pcie2_to_pcie3_wrapper.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_dma_bram_wrap.sv" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/xdma_v3_1/hdl/verilog/PCIe_xdma_0_1_core_top.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xdma_0_1/sim/PCIe_xdma_0_1.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_and.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_carry_or.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_0_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_clk_ibuf.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_infrastructure.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_0_tempmon.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_mux.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_row_col.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_arb_select.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_cntrl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_common.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_compare.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_mach.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_queue.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_bank_state.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_col_mach.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_mc.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_cntrl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_common.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_rank_mach.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_0_round_robin_arb.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_buf.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_gen.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_0_fi_xor.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_0_mem_intfc.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_calib_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_init.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_cc.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_edge_store.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_meta.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_pd.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_tap_base.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_0_poc_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_cmd.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_rd_data.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_top.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_0_ui_wr_data.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/PCIe_mig_7series_0_0_mig_sim.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0/user_design/rtl/PCIe_mig_7series_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_11 $vhdlan_opts \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/5db7/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_0/sim/PCIe_rst_mig_7series_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/f9c1/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/55c0/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/95b9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/f582/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_xbar_0/sim/PCIe_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_proc_sys_reset_0_0/sim/PCIe_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_clock_converter_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/80fd/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_auto_cc_0/sim/PCIe_auto_cc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/f0ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/3bde/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/bcea/hdl/verilog" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/9c7f" +incdir+"$ref_dir/../../../../PCIe.srcs/sources_1/bd/PCIe/ipshared/7e3a/hdl" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_auto_us_1/sim/PCIe_auto_us_1.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_auto_us_0/sim/PCIe_auto_us_0.v" \
    "$ref_dir/../../../bd/PCIe/ip/PCIe_auto_cc_1/sim/PCIe_auto_cc_1.v" \
    "$ref_dir/../../../bd/PCIe/hdl/PCIe.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.PCIe xil_defaultlib.glbl -o PCIe_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./PCIe_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./PCIe.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key PCIe_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc PCIe_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./PCIe.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: PCIe.sh [-help]\n\
Usage: PCIe.sh [-lib_map_path]\n\
Usage: PCIe.sh [-reset_run]\n\
Usage: PCIe.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
