
create_clock -period 5 [get_ports sys_clk_p]

##############reset key define##################
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst]
set_property PACKAGE_PIN T6 [get_ports sys_rst]

set_property PACKAGE_PIN J21 [get_ports {key1}]
set_property IOSTANDARD LVCMOS33 [get_ports {key1}]

set_property PACKAGE_PIN E13 [get_ports {key2}]
set_property IOSTANDARD LVCMOS33 [get_ports {key2}]



############## CMOS define##################
set_property PACKAGE_PIN Y21 [get_ports {cmos1_scl}]
set_property PACKAGE_PIN W21 [get_ports {cmos1_sda}]
set_property PACKAGE_PIN N13 [get_ports {cmos1_reset}]
set_property PACKAGE_PIN R18 [get_ports {cmos1_pclk}]
set_property PACKAGE_PIN R14 [get_ports {cmos1_href}]
set_property PACKAGE_PIN P14 [get_ports {cmos1_vsync}]
set_property PACKAGE_PIN T21 [get_ports {cmos1_d[7]}]
set_property PACKAGE_PIN U21 [get_ports {cmos1_d[6]}]
set_property PACKAGE_PIN V22 [get_ports {cmos1_d[5]}]
set_property PACKAGE_PIN Y19 [get_ports {cmos1_d[4]}]
set_property PACKAGE_PIN Y22 [get_ports {cmos1_d[3]}]
set_property PACKAGE_PIN W19 [get_ports {cmos1_d[2]}]
set_property PACKAGE_PIN W20 [get_ports {cmos1_d[1]}]
set_property PACKAGE_PIN T18 [get_ports {cmos1_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_pclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_reset}]

set_property PACKAGE_PIN AA20 [get_ports {cmos2_reset}]
set_property PACKAGE_PIN W17 [get_ports {cmos2_scl}]
set_property PACKAGE_PIN W15 [get_ports {cmos2_sda}]
set_property PACKAGE_PIN AB21 [get_ports {cmos2_href}]
set_property PACKAGE_PIN T20 [get_ports {cmos2_vsync}]
set_property PACKAGE_PIN Y17 [get_ports {cmos2_pclk}]
set_property PACKAGE_PIN W16 [get_ports {cmos2_d[7]}]
set_property PACKAGE_PIN AB22 [get_ports {cmos2_d[6]}]
set_property PACKAGE_PIN U15 [get_ports {cmos2_d[5]}]
set_property PACKAGE_PIN V17 [get_ports {cmos2_d[4]}]
set_property PACKAGE_PIN AA19 [get_ports {cmos2_d[3]}]
set_property PACKAGE_PIN AB20 [get_ports {cmos2_d[2]}]
set_property PACKAGE_PIN AA21 [get_ports {cmos2_d[1]}]
set_property PACKAGE_PIN V15 [get_ports {cmos2_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_pclk}]

############## LCD define##################
set_property PACKAGE_PIN P16 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN R17 [get_ports {lcd_r[1]}]
set_property PACKAGE_PIN R16 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN P15 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN N17 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN P17 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN U16 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN T16 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN U17 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN U18 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN P19 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN R19 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN V18 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN V19 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN U20 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN V20 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN AA9 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN AB10 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN AA10 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN AA11 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN W10 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN V10 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN Y12 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN Y11 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN W12 [get_ports {lcd_clk}]
set_property PACKAGE_PIN W11 [get_ports {lcd_hs}]
set_property PACKAGE_PIN AA15 [get_ports {lcd_vs}]
set_property PACKAGE_PIN AB15 [get_ports {lcd_en}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_en}]        

      
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]
       
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]